### PR TITLE
Fix problem with billboard stretching when rotating around z axis

### PR DESCRIPTION
**Pull request by runiter**
I originally submitted this fix in Ardor3D forum (before it was taken down) over a year ago. I was promised that it would be tested and added to Ardor3D but I noticed that it is still not added. I figured I make the job easier by pull requesting this time. It's a simple but crucial fix.

### CODE REVIEW

**Comment by runiter** [comment]
nevermind, I noticed it's already apply to gouessej's version:

https://github.com/gouessej/Ardor3D/blob/master/ardor3d-core/src/main/java/com/ardor3d/scenegraph/extension/BillboardNode.java

**Comment by Renanse** [comment]
Thanks, it's good to have it here as well I think

**Comment by runiter** [comment]
Great, thanks Renanse. Glad to see you're still maintaining this repository.

**Comment by gouessej** [comment]
@runiter This fix was merged May 19th 2014 as you can see here: https://github.com/gouessej/Ardor3D/commit/e5cbd7ab638f4e0186f682769166c19a56e45f6c

**Comment by gouessej** [comment]
@Renanse I just wanted to be accurate. Of course, feel free to put the few other fixes into this repository too.

**Comment by runiter** [comment]
@Renanse is there any chance you can update Ardor3D maven repository with the latest version as produced by @gouessej in his repository? In the past it's been very convenient to have Ardor3D on maven. It's a shame that I can't use it anymore.

**Comment by gouessej** [comment]
@runiter I remind you that Ardor3D and JogAmp's Ardor3D Continuation are 2 distinct engines. In my humble opinion, it makes no sense to replace the last Ardor3D build by something noticeably different. It contains some breaking changes, I removed a whole sub-project, I moved some classes into some separate sub-projects, they don't support exactly the same build tools (the latter supports Gradle too), they don't behave exactly the same (especially under Mac) and @Renanse is free to disagree with my design choices.

However, I understand your concern, we (JogAmp) can put the latter into our Maven development repository (not on Maven Central to avoid any confusion) but it isn't the best place to talk about that.

**Comment by Renanse** [comment]
Julien is trying hard to differentiate his fork, so I'd rather not mix
those streams.

**Pull request merged**
